jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cache Maven Repos
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - continue-on-error: true
      name: Build with Maven
      run: mvn --batch-mode --no-transfer-progress clean install cobertura:cobertura
        -Dmaven.javadoc.skip=true
    - continue-on-error: true
      uses: codecov/codecov-action@v1
name: build
on:
  repository_dispatch:
    types: trigger-ga___main.yml
